import {
  Body,
  Controller,
  Get,
  Param,
  Patch,
  Post,
  Put,
  Query,
  UseGuards,
} from '@nestjs/common';
import {
  ApiBadRequestResponse,
  ApiBody,
  ApiConflictResponse,
  ApiCookieAuth,
  ApiCreatedResponse,
  ApiForbiddenResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiQuery,
  ApiTags,
  ApiUnauthorizedResponse,
} from '@nestjs/swagger';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard.js';
import { type InternalAuthUser } from '../auth/auth-user.js';
import { CurrentUser } from '../auth/decorators/current-user.decorator.js';
import { AUTH_COOKIE_NAME } from '../auth/auth.constants.js';
import { PermissionGuard } from '../authorization/permission.guard.js';
import { RequirePermissions } from '../authorization/require-permissions.decorator.js';
import type {
  CreatePlatformUserBody,
  ListPlatformUsersQuery,
  ReplacePlatformUserRolesBody,
  SetPlatformUserStatusBody,
  UpdatePlatformUserBody,
} from './platform-users.schemas.js';
import {
  createPlatformUserSchema,
  listPlatformUsersQuerySchema,
  replacePlatformUserRolesSchema,
  setPlatformUserStatusSchema,
  updatePlatformUserSchema,
} from './platform-users.schemas.js';
import { PlatformUsersService } from './platform-users.service.js';
import {
  CREATE_PLATFORM_USER_BODY_SCHEMA,
  PLATFORM_USER_EXAMPLE,
  PLATFORM_USER_ROLE_SCHEMA,
  PLATFORM_USER_SCHEMA,
  REPLACE_PLATFORM_USER_ROLES_BODY_SCHEMA,
  REPLACE_PLATFORM_USER_ROLES_SCHEMA,
  SET_PLATFORM_USER_STATUS_BODY_SCHEMA,
  UPDATE_PLATFORM_USER_BODY_SCHEMA,
} from './platform-users.swagger.js';
import type {
  PlatformUserResponse,
  PlatformUserRoleRef,
  ReplacePlatformUserRolesResponse,
} from './platform-users.types.js';

const CODE_PARAM = {
  name: 'code',
  description: 'Platform user code',
  example: PLATFORM_USER_EXAMPLE.code,
};

@ApiTags('platform-users')
@Controller('platform-users')
@UseGuards(JwtAuthGuard, PermissionGuard)
@ApiCookieAuth(AUTH_COOKIE_NAME)
@ApiUnauthorizedResponse({ description: 'Missing, invalid or expired auth cookie' })
@ApiForbiddenResponse({ description: 'Authenticated but missing the required permission' })
export class PlatformUsersController {
  constructor(private readonly platformUsersService: PlatformUsersService) {}

  @Get()
  @RequirePermissions('PLATFORM_USER_VIEW')
  @ApiOperation({ summary: 'List platform users' })
  @ApiQuery({
    name: 'search',
    required: false,
    description: 'Matches code, email, first name or last name (case-insensitive)',
    example: 'support',
  })
  @ApiOkResponse({
    description: 'Platform users with their role assignments, newest first',
    schema: { type: 'array', items: PLATFORM_USER_SCHEMA },
  })
  list(
    @Query({ schema: listPlatformUsersQuerySchema }) query: ListPlatformUsersQuery,
  ): Promise<PlatformUserResponse[]> {
    return this.platformUsersService.list(query);
  }

  @Get(':code')
  @RequirePermissions('PLATFORM_USER_VIEW')
  @ApiOperation({ summary: 'Get a single platform user' })
  @ApiParam(CODE_PARAM)
  @ApiOkResponse({ description: 'The requested platform user', schema: PLATFORM_USER_SCHEMA })
  @ApiNotFoundResponse({ description: 'Platform user not found' })
  getByCode(@Param('code') code: string): Promise<PlatformUserResponse> {
    return this.platformUsersService.getByCode(code);
  }

  @Get(':code/roles')
  @RequirePermissions('PLATFORM_USER_ROLE_VIEW')
  @ApiOperation({ summary: 'List the platform roles assigned to a platform user' })
  @ApiParam(CODE_PARAM)
  @ApiOkResponse({
    description: 'Platform Role assignments (sorted by role name)',
    schema: { type: 'array', items: PLATFORM_USER_ROLE_SCHEMA },
  })
  @ApiNotFoundResponse({ description: 'Platform user not found' })
  listRoles(@Param('code') code: string): Promise<PlatformUserRoleRef[]> {
    return this.platformUsersService.listRoles(code);
  }

  @Post()
  @RequirePermissions('PLATFORM_USER_CREATE')
  @ApiOperation({
    summary: 'Create a platform user',
    description:
      'Creates the AppUser and its initial Platform Role assignments atomically. ' +
      'The code is generated by the backend; status is always ACTIVE. ' +
      'The password hash is stored with argon2 and is never returned or logged.',
  })
  @ApiBody({ description: 'At least one existing PLATFORM role key is required.', schema: CREATE_PLATFORM_USER_BODY_SCHEMA })
  @ApiCreatedResponse({ description: 'Platform user created', schema: PLATFORM_USER_SCHEMA })
  @ApiConflictResponse({ description: 'An AppUser with this email already exists' })
  @ApiBadRequestResponse({
    description: 'Unknown role keys, AGENCY role keys, or an empty roleKeys array',
  })
  create(
    @Body({ schema: createPlatformUserSchema }) dto: CreatePlatformUserBody,
  ): Promise<PlatformUserResponse> {
    return this.platformUsersService.create(dto);
  }

  @Patch(':code')
  @RequirePermissions('PLATFORM_USER_UPDATE')
  @ApiOperation({
    summary: 'Update a platform user profile (email, first name, last name)',
    description:
      'Only profile fields are accepted. The code, password, account status and role assignments ' +
      'are immutable here and have dedicated endpoints.',
  })
  @ApiParam(CODE_PARAM)
  @ApiBody({ description: 'At least one field is required.', schema: UPDATE_PLATFORM_USER_BODY_SCHEMA })
  @ApiOkResponse({ description: 'Platform user updated', schema: PLATFORM_USER_SCHEMA })
  @ApiNotFoundResponse({ description: 'Platform user not found' })
  @ApiConflictResponse({ description: 'Email is already in use by another AppUser' })
  update(
    @Param('code') code: string,
    @Body({ schema: updatePlatformUserSchema }) dto: UpdatePlatformUserBody,
  ): Promise<PlatformUserResponse> {
    return this.platformUsersService.update(code, dto);
  }

  @Patch(':code/status')
  @RequirePermissions('PLATFORM_USER_DISABLE')
  @ApiOperation({
    summary: 'Set the account status of a platform user (suspend or reactivate)',
    description:
      'SUSPENDED is effective immediately: the user can no longer log in and existing ' +
      'sessions are rejected on the next request because the JWT is identity-only and ' +
      'the status is re-read from the database. A user cannot suspend their own account.',
  })
  @ApiParam(CODE_PARAM)
  @ApiBody({ schema: SET_PLATFORM_USER_STATUS_BODY_SCHEMA })
  @ApiOkResponse({ description: 'Platform user status updated', schema: PLATFORM_USER_SCHEMA })
  @ApiNotFoundResponse({ description: 'Platform user not found' })
  @ApiBadRequestResponse({
    description: 'Attempting to suspend your own account (CANNOT_SUSPEND_OWN_ACCOUNT)',
  })
  setStatus(
    @Param('code') code: string,
    @Body({ schema: setPlatformUserStatusSchema }) dto: SetPlatformUserStatusBody,
    @CurrentUser() currentUser: InternalAuthUser,
  ): Promise<PlatformUserResponse> {
    return this.platformUsersService.setStatus(code, dto, currentUser.id);
  }

  @Put(':code/roles')
  @RequirePermissions('PLATFORM_USER_ROLE_MANAGE')
  @ApiOperation({
    summary: 'Replace all platform roles of a platform user (atomic)',
    description:
      'The provided role keys replace the full assignment set. Duplicate keys are reduced; at least ' +
      'one key is required so a platform user can never be left without any assignment through this endpoint. ' +
      'Only existing PLATFORM roles are assignable; AGENCY roles and unknown keys are rejected.',
  })
  @ApiParam(CODE_PARAM)
  @ApiBody({ schema: REPLACE_PLATFORM_USER_ROLES_BODY_SCHEMA })
  @ApiOkResponse({
    description: 'The final effective role assignments',
    schema: REPLACE_PLATFORM_USER_ROLES_SCHEMA,
  })
  @ApiNotFoundResponse({ description: 'Platform user not found' })
  @ApiBadRequestResponse({
    description: 'Unknown role keys, AGENCY role keys, or an empty roleKeys array',
  })
  replaceRoles(
    @Param('code') code: string,
    @Body({ schema: replacePlatformUserRolesSchema }) dto: ReplacePlatformUserRolesBody,
  ): Promise<ReplacePlatformUserRolesResponse> {
    return this.platformUsersService.replaceRoles(code, dto);
  }
}