import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/components/header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Temporary demo branding — remove once the platform delivers agency branding.
const DEMO_AGENCY = {
  agencyName: "Sahara",
  primaryColor: "#0f766e",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header
          agencyName={DEMO_AGENCY.agencyName}
          primaryColor={DEMO_AGENCY.primaryColor}
          navLinks={[
            { label: "Tours", href: "#tours" },
            { label: "Destinations", href: "#destinations" },
            { label: "About", href: "#about" },
            { label: "Contact", href: "#contact" },
          ]}
        />
        {children}
      </body>
    </html>
  );
}